### ISSUE TITLE
EIS Types

### ISSUE THREAD

**Issue by remcollier** [agentcontest/massim#10]
Hi guys,

Thanks for the previous fix - we have been playing with the new server - it is very nice.

I just have one thought - I tried to use the EIS method for getting the type of an entity, but it returns "unknown". Is this deliberate, or would it be possible to return the type (e.g. "drone") as this would allow me to assign the correct agent program to each entity without needing to manually map id's to types...

Rem

**Comment by t-ah** [comment]
Hi Rem,

when do you need this information? We could set the type when eismassim receives the sim-start messages. But this might be too late for you?

Tobias

**Comment by remcollier** [comment]
this would be too late - i was thinking that might have been the problem (you don't know the type until you receive the first message).  I will revert to using id->type mappings (I was trying to generalise the agent code as much as possible so that you only need to know types, but it is not a big deal.

Thanks for the reply, Rem
