### ISSUE TITLE
Problem with EIS item(...) percept

### ISSUE THREAD

**Issue by remcollier** [agentcontest/massim#11]
Hi,

I am having an issue with the EIS item(...) percept.

XML:

    <item name="item9" volume="6">
      <item>item1</item>
      <item>item7</item>
      <item>item6</item>
      <item>item0</item>
      <item>item4</item>
      <role>motorcycle</role>
      <role>truck</role>
    </item>

IILang:

item(item9,6,roles([,]),parts([,,,,]))

The values seem to be lost in translation from XML to IILang...

Rem

**Comment by t-ah** [comment]
Hi Rem,

just to be sure, I assume it is the item percept from Sim-Start? 
How and where do you obtain the IILang string? When I print it right after it was generated it looks fine.
Do you have this with all item percepts?

Tobias

**Comment by remcollier** [comment]
Its not so simple. EIS is integrated into my AOP language ASTRA:

 if (ei.getState().equals(EnvironmentState.RUNNING)) {
	try {
		Collection<String> entities = ei.getAssociatedEntities(agent.name());
		System.out.println("entities: " + entities);
		if (!entities.isEmpty()) {
		    	return ei.getAllPercepts(agent.name(), entities.toArray(new String[entities.size()]));
		}
	} catch (AgentException e) {
		logger.log(Level.WARNING, "[" + agent.name() + "] Agent Problem: " + e.getMessage(), e);
	}
 }

This returns a map whose output looks like this:

{connectionA1=[item(item2,9,roles([]),parts([])), maxLat(48.9), item(item0,7,roles([]),parts([])), upgrade(battery,300,5), simStart, upgrade(speed,1000,1), item(item4,5,roles([]),parts([])), item(item8,10,roles([,]),parts([,])), item(item10,7,roles([,]),parts([,,])), team(A), wellType(wellType4,2112,17,35,71), id(2018-SampleSimulation), name(agentA1), minLon(2.26), item(item7,5,roles([,]),parts([,,,,])), item(item9,6,roles([,]),parts([,,,,])), upgrade(load,200,10), centerLat(48.8424), proximity(5), wellType(wellType1,1082,8,32,65), minLat(48.82), item(item3,7,roles([]),parts([])), map(paris), item(item1,5,roles([]),parts([])), centerLon(2.3209), wellType(wellType3,1546,12,43,87), steps(1000), seedCapital(5000), wellType(wellType0,600,4,36,73), upgrade(skill,1000,1), item(item5,5,roles([,]),parts([,])), maxLon(2.41), cellSize(200.0), item(item6,5,roles([,]),parts([,,,,])), upgrade(vision,1000,50), role(drone,5,7,15,25,1,3,600,1000,20,40), wellType(wellType2,1431,11,48,96), job(job479,storage3,463,463,541,[required(item5,2),required(item6,2),required(item9,3)]), job(job482,storage3,379,473,531,[required(item6,1),required(item7,2),required(item8,1),required(item9,2)]), job(job481,storage2,384,468,537,[required(item10,3),required(item6,1),required(item8,4),required(item9,1)]), job(job485,storage3,415,478,538,[required(item10,2),required(item5,1),required(item9,2)]), dump(dump0,48.85587,2.32361), speed(5), deadline(1532361188063), route([]), chargingStation(chargingStation5,48.88577,2.34642,35), job(job471,storage3,378,441,525,[required(item10,1),required(item5,1),required(item6,2),required(item8,2),required(item9,1)]), chargingStation(chargingStation2,48.85742,2.3726,24), shop(shop2,48.85095,2.40201), job(job477,storage0,269,458,545,[required(item8,2),required(item9,1)]), step(480), workshop(workshop3,48.89408,2.40692), skill(1), lastActionResult(successful), requestAction, chargingStation(chargingStation1,48.85317,2.31813,33), auction(job483,storage1,370,476,556,370,0,5,[required(item5,1),required(item6,3),required(item7,1),required(item9,1)]), maxLoad(15), shop(shop6,48.86342,2.39246), job(job476,storage3,431,456,513,[required(item10,1),required(item8,1),required(item9,3)]), chargingStation(chargingStation0,48.83015,2.28473,22), job(job473,storage0,210,448,544,[required(item10,1),required(item7,2),required(item8,1)]), job(job480,storage1,326,467,547,[required(item10,2),required(item5,5),required(item6,1),required(item7,1),required(item8,1)]), entity(agentA1,A,48.862,2.37507,drone), timestamp(1532361184063), shop(shop0,48.84675,2.31271), shop(shop5,48.86151,2.37592), job(job467,storage0,366,420,495,[required(item10,1),required(item5,1),required(item6,1),required(item7,2),required(item8,1),required(item9,1)]), maxBattery(20), chargingStation(chargingStation4,48.87003,2.28371,27), vision(600), job(job466,storage2,182,417,481,[required(item10,1),required(item7,1)]), job(job474,storage2,298,454,516,[required(item5,1),required(item6,2),required(item9,1)]), lastActionParams([]), storage(storage0,48.8242,2.30026,10271,0,[]), workshop(workshop0,48.82453,2.28949), workshop(workshop2,48.83966,2.38397), actionID(1480), score(0), lon(2.37507), charge(20), facility(), job(job468,storage3,331,432,497,[required(item6,2),required(item7,1),required(item9,2)]), job(job460,storage0,409,403,498,[required(item6,2),required(item7,2),required(item8,1),required(item9,2)]), job(job484,storage0,439,477,572,[required(item10,1),required(item5,1),required(item6,1),required(item7,2),required(item8,1),required(item9,2)]), shop(shop4,48.88958,2.30934), dump(dump2,48.87214,2.40587), lastAction(noAction), shop(shop3,48.87675,2.27393), lat(48.862), massium(4529), entity(agentC1,C,48.862,2.37507,drone), storage(storage2,48.86243,2.30345,9401,0,[]), job(job464,storage3,238,413,506,[required(item10,1),required(item6,1),required(item7,1)]), routeLength(0), storage(storage3,48.86627,2.40691,9797,0,[]), chargingStation(chargingStation3,48.84793,2.39448,33), job(job463,storage3,244,412,511,[required(item10,2),required(item6,1),required(item7,1)]), shop(shop1,48.83829,2.35044), storage(storage1,48.82745,2.3717,11049,0,[]), load(0), workshop(workshop1,48.82456,2.31017), dump(dump1,48.88682,2.32883)]}

**Comment by remcollier** [comment]
Wrote the following program and got the same output (using EIS0.5 & EIS0.6):

import eis.EnvironmentInterfaceStandard;
import eis.exceptions.AgentException;
import eis.exceptions.ManagementException;
import eis.exceptions.NoEnvironmentException;
import eis.exceptions.PerceiveException;
import eis.exceptions.RelationException;
import massim.eismassim.EnvironmentInterface;

public class Test {
	public static void main(String[] args) throws ManagementException, AgentException, RelationException, PerceiveException, NoEnvironmentException {
		EnvironmentInterfaceStandard ei = new EnvironmentInterface();
		ei.start();
		ei.registerAgent("connectionA1");
		ei.associateEntity("connectionA1", "connectionA1");
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		System.out.println("Percepts: " + ei.getAllPercepts("connectionA1", "connectionA1"));
	}
}

**Comment by t-ah** [comment]
Thanks.
I now believe you have different protocol versions of the massim server and eismassim (we minimally changed the structure with 6385789653b2f12810f4f1e023c35d3d648aa4b1). So probably your eismassim is expecting the new structure (with name attributes in the xml) while your server provides the older one.

**Comment by remcollier** [comment]
Ah - I used the snapshot version of the server from issue #9 and this resolved the problem (i had been using the new EIS environment with the old release 1.0 of the server).

Thanks (again), Rem
