### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by hypnobunny** [agentcontest/massim#3]
Hi there,

Are there plans to publish the MASSim packages to Maven Central or the like? This will decrease the barrier of entry somewhat for accessing the MASSim libraries.

Cheers,
Matthew McNally

**Comment by niklasf** [comment]
Hi,

do you think https://jitpack.io/#agentcontest/massim is suitable? This way we could avoid maintaining a seperate Maven repo.

Best,
Niklas
